# Ref:
# https://answers.ros.org/question/326628/how-to-control-velocity-of-joints-in-gazebo-using-ros_controllers/

left_controller:
  ros_parameters:
    type: velocity_controllers/JointVelocityController
    joint: roda_esq_joint

right_controller:
  ros_parameters:
    type: velocity_controllers/JointVelocityController
    joint: roda_dir_join