controller_manager:
  ros__parameters:
    pid_gains:
      roda_esq_joint:
        p: 0.015
        i: 1.0
        d: 0.0
        antiwindup: true
        i_clamp_max: 0.1
        i_clamp_min: -0.1
      roda_dir_joint:
        p: 0.015
        i: 1.0
        d: 0.0
        antiwindup: true
        i_clamp_max: 0.1
        i_clamp_min: -0.1